//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerRole
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartNewsEntities : DbContext
    {
        public SmartNewsEntities()
            : base("name=SmartNewsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Cluster> Clusters { get; set; }
        public virtual DbSet<Filter> Filters { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<NewsSource> NewsSources { get; set; }
        public virtual DbSet<Preference> Preferences { get; set; }
        public virtual DbSet<ToReadList> ToReadLists { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
